# ==============================================================================
# Azimuth -- Web App Embedder
# Compresses index.html and writes webapp_gz.h
# Run this whenever the web app HTML changes, then recompile in Arduino IDE.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\make_webapp.ps1
#
# Place this script in the firmware folder alongside webapp_gz.h
# It expects index.html to be in ../webapp/index.html
# ==============================================================================

$ErrorActionPreference = "Stop"

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$HtmlFile   = Join-Path $ScriptDir "..\webapp\index.html"
$HeaderFile = Join-Path $ScriptDir "webapp_gz.h"

if (-not (Test-Path $HtmlFile)) {
    Write-Host "ERROR: ../webapp/index.html not found." -ForegroundColor Red
    Write-Host "       Expected path: $HtmlFile" -ForegroundColor Yellow
    exit 1
}

# Find Python -- skip Microsoft Store stub
$PythonCandidates = @(
    "$env:LOCALAPPDATA\Arduino15\packages\python\tools\python3\*\python3.exe",
    "$env:LOCALAPPDATA\Programs\Python\Python3*\python.exe",
    "$env:LOCALAPPDATA\Programs\Python\Python*\python.exe",
    "C:\Python3*\python.exe",
    "C:\Python*\python.exe"
)
$Python = $null
foreach ($p in $PythonCandidates) {
    $found = Get-Item $p -ErrorAction SilentlyContinue | Select-Object -First 1 -ExpandProperty FullName
    if ($found) { $Python = $found; break }
}
if (-not $Python) {
    $fromPath = Get-Command python -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source
    if ($fromPath -and $fromPath -notlike "*WindowsApps*") { $Python = $fromPath }
}
if (-not $Python) {
    Write-Host "ERROR: Python not found. Install from https://python.org" -ForegroundColor Red; exit 1
}

Write-Host "Using Python: $Python" -ForegroundColor Cyan
Write-Host "Input:  $HtmlFile" -ForegroundColor Cyan
Write-Host "Output: $HeaderFile" -ForegroundColor Cyan

$PyScript = @'
import gzip, sys, os
with open(sys.argv[1], "rb") as f:
    raw = f.read()
compressed = gzip.compress(raw, compresslevel=9)
pct = round((1 - len(compressed)/len(raw)) * 100)
print("  " + os.path.basename(sys.argv[1]) + ": " + str(len(raw)) + " bytes -> " + str(len(compressed)) + " bytes (" + str(pct) + "% smaller)")
lines = [
    "#ifndef WEBAPP_GZ_H",
    "#define WEBAPP_GZ_H",
    "",
    "// Auto-generated by make_webapp.ps1 -- do not edit manually",
    "// Web app HTML (gzip compressed) embedded in firmware",
    "// Original: " + str(len(raw)) + " bytes, Compressed: " + str(len(compressed)) + " bytes",
    "",
    "const uint8_t WEBAPP_GZ[] PROGMEM = {"
]
hex_bytes = ["0x{:02X}".format(b) for b in compressed]
for i in range(0, len(hex_bytes), 16):
    lines.append("    " + ", ".join(hex_bytes[i:i+16]) + ",")
lines.append("};")
lines.append("")
lines.append("const uint32_t WEBAPP_GZ_LEN = " + str(len(compressed)) + ";")
lines.append("")
lines.append("#endif // WEBAPP_GZ_H")
with open(sys.argv[2], "w") as f:
    f.write("\n".join(lines))
'@

$TmpPy = Join-Path $env:TEMP "make_webapp.py"
$PyScript | Set-Content $TmpPy -Encoding UTF8
& $Python $TmpPy $HtmlFile $HeaderFile
Remove-Item $TmpPy -ErrorAction SilentlyContinue

if (Test-Path $HeaderFile) {
    Write-Host "  webapp_gz.h written. Recompile in Arduino IDE to embed the update." -ForegroundColor Green
} else {
    Write-Host "  ERROR: webapp_gz.h not created." -ForegroundColor Red; exit 1
}
